### ISSUE TITLE
Cheatsheet request: Kotlin

### ISSUE THREAD

**Issue by bishbi** [Fechin/reference#20]
## A clear description of what you want
- would like to request another cheatsheet about Kotlin 
- Java
- and VUE . as simple like your php and javascript

Thanks

**Comment by Fechin** [comment]
Hi there! Just wanted to let you know that a draft for Kotlin has been published at https://quickref.me/kotlin. Check it out and feel free to provide any feedback or suggestions by submitting an issue on Github. Thanks!
