### ISSUE TITLE
Cheatsheet request: 

### ISSUE THREAD

**Issue by Pickacho** [Fechin/reference#209]
Please create a Kubernetes + Docker cheatsheet

**Comment by Lukas2112** [comment]
Please mention behind "Cheatsheet request:" for which programming language or similar a guide should be created, @Pickacho

**Comment by Fechin** [comment]
Please check https://quickref.me/kubernetes, https://quickref.me/docker, If you see the cheatsheet is not fit, you can fix it by submitting a [PR](https://github.com/Fechin/reference#contributing). Thanks!
