### ISSUE TITLE
Cheatsheet request: 

### ISSUE THREAD

**Issue by Ranjan667** [Fechin/reference#228]
C programming

**Comment by Lukas2112** [comment]
Please mention behind "Cheatsheet request:" for which programming language or similar a guide should be created, @Ranjan667  .

**Comment by Ranjan667** [comment]
C programming language

**Comment by Fechin** [comment]
Please check [https://quickref.me/c](https://quickref.me/c), If you see the cheatsheet is not fit, you can fix it by submitting a [PR](https://github.com/Fechin/reference#contributing). Thanks!
