### ISSUE TITLE
Cheatsheet request: Latex

### ISSUE THREAD

**Issue by manning120008** [Fechin/reference#23]
Latex quickreference

**Comment by matu3ba** [comment]
[Is this too dense](http://tug.ctan.org/info/latex-refsheet/LaTeX_RefSheet.pdf) ?

**Comment by Fechin** [comment]
Please check https://quickref.me/latex, If you see the cheatsheet is not fit, you can fix it by submitting a [PR](https://github.com/Fechin/reference#contributing). Thanks!
