### ISSUE TITLE
Cheatsheet request: perl 

### ISSUE THREAD

**Issue by pineapples5972** [Fechin/reference#232]
Please add perl language cheatsheet
yes it still being used today.

Here are some references for cheatsheets: 
- https://perldoc.perl.org/perlcheat
- https://www.programming-idioms.org/cheatsheet/Perl
- https://perlmaven.com/regex-cheat-sheet

**Comment by Fechin** [comment]
Check it out at https://cheatsheets.zip/perl, it's still a work in progress.
