### ISSUE TITLE
Cheatsheet request: 

### ISSUE THREAD

**Issue by ssakgul** [Fechin/reference#242]
I want to learn Latex. Is it possible to prepare a cheatsheet about it?

**Comment by Lukas2112** [comment]
Please mention behind "Cheatsheet request:" for which programming language or similar a guide should be created, @ssakgul .

**Comment by Fechin** [comment]
Please check https://quickref.me/latex, If you see the cheatsheet is not fit, you can fix it by submitting a [PR](https://github.com/Fechin/reference#contributing). Thanks!
