### ISSUE TITLE
Hello, can you give a configuration file of nginx conf?

### ISSUE THREAD

**Issue by 92000** [Fechin/reference#314]
Or is there a way to generate index.html from the html file and put it in the corresponding directory when building.

Some scenarios do not allow configuration of nginx pseudo-static.

**Comment by 92000** [comment]
@Fechin

**Comment by Fechin** [comment]
Thank you! It's a good question. For most cases, trailing `.html` seems to be needed here. So I made it default in f3633415b8a515e48a1fdeca83edc2790390a2cc commits.

**Comment by 92000** [comment]
> Thank you! It's a good question. For most cases, trailing `.html` seems to be needed here. So I made it default in [f363341](https://github.com/Fechin/reference/commit/f3633415b8a515e48a1fdeca83edc2790390a2cc) commits.

Thanks! Just built it and it helped me a lot.
