### ISSUE TITLE
Cheatsheet request: Google

### ISSUE THREAD

**Issue by OcelusPRO** [Fechin/reference#345]
Google searches are very powerful tools when they are well mastered, we generally all know that adding "" around certain terms will force google to display pages containing this precise string, but this is only part of the possibilities , you can force the search via specific domains, file extensions, etc.

It seems to me very interesting to propose a documentation here for google

**Comment by OcelusPRO** [comment]
I found this as documentation, it seems to me that there are still other parameters available

https://support.google.com/websearch/answer/2466433

**Comment by Fechin** [comment]
Please check https://quickref.me/google-search, If you see the cheatsheet is not fit, you can fix it by submitting a [PR](https://github.com/Fechin/reference#contributing). Thanks!
