### ISSUE TITLE
EJS Loop

### ISSUE THREAD

**Issue by greencodecomments** [Fechin/reference#453]
On the EJS Cheatsheet, the Loop section shows an IF statement, not a Loop.

Suggest changing it to something like this:
```
<ul>
<% for(i=0; i < users.length; i++) { %>
  <li> <%= users[i].username %> </li>
<% } %>
</ul> 
```

**Comment by Fechin** [comment]
Thank you for bringing this to our attention. 

Please check this https://cheatsheets.zip/ejs#using-loops
