### ISSUE TITLE
nc encrypted transfer example is incorrect

### ISSUE THREAD

**Issue by gagzilla** [Fechin/reference#468]
The example for encrypted transfer with nc and openssl is incorrect. Here is the correct implementation-

For server- $ openssl enc -des3 -in file.txt -pass pass:password | nc -l 8000
For client- $ nc 192.168.1.9 8000 | openssl enc -des3 -d -pass pass:password -out file.txt

I should have a PR shortly to fix this.

**Comment by Fechin** [comment]
Thank you for addressing the issue.
