### ISSUE TITLE
Cheatsheet enhancement: React js include Hooks sections

### ISSUE THREAD

**Issue by zehan12** [Fechin/reference#491]
**Issue Description**:
I propose adding a new section to the cheatsheet that covers React.js Hooks. React Hooks are essential for modern React development, and having a concise reference in our cheatsheet would be highly beneficial for developers. This section should include the following subsections:

1. **State Hook**:
   - Explanation of the `useState` Hook.
   - Example code illustrating how to use it.

2. **Multiple State Variable Declaration**:
   - Explanation of declaring and using multiple state variables with `useState`.
   - Example code demonstrating the concept.

3. **Input State Management**:
   - Tips and best practices for managing input state in React components.
   - Example code showcasing input state management using Hooks.

4. **useEffect**:
   - Explanation of the `useEffect` Hook.
   - Common use cases and scenarios where it is useful.
   - Example code demonstrating the usage of `useEffect`.

5. **Build Your Own Hooks**:
   - Introduction to custom Hooks creation.
   - Guidelines and best practices for building custom Hooks.
   - Example code for creating a custom Hook.

**Benefits**:
- Provides developers with a comprehensive reference for React Hooks.
- Makes it easier for both beginners and experienced React developers to understand and utilize Hooks effectively.
- Enhances the overall usability of our cheatsheet.

**Assignees**: @zehan12

**Comment by zehan12** [comment]
@Fechin  Can I add up the documentation for React?

**Comment by Fechin** [comment]
@zehan12 Thanks for your suggestion, feel free to add whatever you'd like!
