### ISSUE TITLE
PR for the Selenium Cheat Sheet is not appearing in search results on the website, even though it's visible in the GitHub repository.

### ISSUE THREAD

**Issue by deepshah201** [Fechin/reference#523]
@Fechin, I have created a pull request for the Selenium Cheat Sheet, and it is visible in the GitHub repository. However, when I try to search for it on the website, the result is not showing up.

Please take a look 
[https://github.com/Fechin/reference/pull/522](url)

![image](https://github.com/Fechin/reference/assets/84764353/21aef115-89b6-4eed-acc9-0449c7d78b46)

**Comment by Fechin** [comment]
Thank you for your contribution. Based on the official domain of the repository, the cheat sheet you contributed can be viewed here: https://cheatsheets.zip/selenium

**Comment by deepshah201** [comment]
Found it Thank you @Fechin
