### ISSUE TITLE
Add formatter

### ISSUE THREAD

**Issue by FireIsGood** [Fechin/reference#526]
Over all the pages and layout files, lots of spacing and minor changes are inconsistent. One solution to this might be a formatter to run over the code.

One option I would lean towards would be a more opinionated one such as Prettier. I have made a branch on my local fork to show what this would look like.

Lint commit example: https://github.com/FireIsGood/reference/commit/aade5279902dd32d632816a40ff4ce593c9cbebd

Changes might be as follows:

> Header style changes
> (underline dash to prefix pound sign)

```diff
- 
- Getting Started
- --------
+ ## Getting Started
```

> Frontmatter changes
> (consistent quotation type)

```diff
- title: 'Cheatsheet request: '
+ title: "Cheatsheet request: "
```

> Table fixes
> (Formatted nicely!)

```diff
- Shortcut | Action
- ---|---
- `K/J`  | Move Up/Down
- `H`  | Jump to Inbox tab
- `S`  | Jump to Archive tab
- `F`  | Follow or Unfollow
- `I`  | Archive
- `U`  | Move to Inbox
+ | Shortcut | Action              |
+ | -------- | ------------------- |
+ | `K/J`    | Move Up/Down        |
+ | `H`      | Jump to Inbox tab   |
+ | `S`      | Jump to Archive tab |
+ | `F`      | Follow or Unfollow  |
+ | `I`      | Archive             |
+ | `U`      | Move to Inbox       |
+ 
```

## Concerns

Currently the style guide recommends using a full underline of dash characters `-` to make the `h2` level headings. The example of prettier would have all of these converted to using the two pound sign prefix version.

Some assorted files have slight formatting errors that may trip up the formatter. One example I found was the `chatgpt` file which had some very specific markdown code block issues due to its specific format.

No formatted:

```md
- **Choose a random contest winner(s) from a long list of names or emails**
    ``` {.wrap}
    I want to choose a winner from a list of 100 names, can you help?
    ```
    ``` {.wrap}
    Can you randomly pick 5 email addresses from a list of 1000 for a giveaway contest?
    ```
{.collapsible}
```

Automatic format:

```md
- **Choose a random contest winner(s) from a long list of names or emails**
  `{.wrap}
 I want to choose a winner from a list of 100 names, can you help?
`
  `{.wrap}
 Can you randomly pick 5 email addresses from a list of 1000 for a giveaway contest?
`
  {.collapsible}
```

## Required Changes

If the project were to adopt something like `prettier`, a new script in the `package.json` would have to be made such as `format`. To make sure it runs on every commit, a tool such as [Husky](https://typicode.github.io/husky/) could be employed pretty simply, though that would also make users sit through a ~7 second commit process every commit as the program scanned all the files.

The style guide may have to be changed slightly, though it seems that due to embedding other files it would be fine from a brief glance.

A full review of the changes would be required for the first lint, though subsequent lints would be fixed by the authors.

---

If this sounds like a good idea, I could make a pull request with all the proposed changes.

**Comment by Fechin** [comment]
Thank you for your suggestion, I think it's great. Prettier can help maintain code cleanliness. I look forward to seeing your PR. As you mentioned, a thorough review of the changes would be necessary for the initial lint.

**Comment by FireIsGood** [comment]
I've begun work on this and it seems that the tons of legacy code are messing up the automatic formatting powers. I've done a bunch of manual edits and it seems like around half of them will need manual fixing either for existing issues or issues that appear prettier is run.

Also, I was not sure exactly what Prettier settings you would prefer. Since it is an opinionated formatter, I set it with minimal defaults except for a `print width` of 120 characters (matches the `Laravel` lines of text in the README wrapping, though with a more conventional wrap count) and always wrapped the prose.

On the subject of making sure further commits actually follow the linting, do you think adding something like [Husky](https://typicode.github.io/husky/) would be a good idea for that pull request, another pull request, or not at all? Without a tool like that, users would have to remember to run `npm run format` after changes or others will have errors not caused by them.

Here's the commits of the branch if you want to track my progress: https://github.com/FireIsGood/reference/commits/prettier/
