### ISSUE TITLE
MongoDB cheatsheet contains Deprecated Methods

### ISSUE THREAD

**Issue by RishiSharmapro** [Fechin/reference#564]
I wanted to remind you about the **MongoDB cheatsheet**, specifically the **"Crud" section which includes Deprecated Methods** such as:
>1. **db.collection.remove()**
>2. **db.collection.update()**

I've also attached a screenshot of the **MongoDB cheatsheet** that highlights the **deprecated methods**, as well as another screenshot showing the **alternative methods**.
#
<img width="1470" alt="Screenshot 2024-06-22 at 5 11 54 PM" src="https://github.com/Fechin/reference/assets/86489633/6a6b3cc5-7c8a-4c3b-963d-8b091042a2dc">

#

<img width="1419" alt="Screenshot 2024-06-22 at 5 53 07 PM" src="https://github.com/Fechin/reference/assets/86489633/00d39359-ec60-4213-9255-d2b8622caadd">
<img width="1419" alt="Screenshot 2024-06-22 at 5 53 23 PM" src="https://github.com/Fechin/reference/assets/86489633/66850e44-49d1-43c1-92e9-98ea83ced542">

##
***Link to the official site: https://www.mongodb.com/docs/mongodb-shell/reference/compatibility/#deprecated-methods***

**Comment by RishiSharmapro** [comment]
@Fechin, I would like to make the necessary correction :)
Please assign it to me

**Comment by Fechin** [comment]
Assigned. Thank you.
