### ISSUE TITLE
Please clarify the relationship between cheatsheets.zip and quickref.me

### ISSUE THREAD

**Issue by ernstki** [Fechin/reference#583]
Hi, @fechin and @Randy8080. Hope you're doing all right. Thanks for all your work here.

Can you please clarify—preferably in the README—the relationship between quickref.me and cheatsheets.zip?

One looks to be the other, basically, except:

* quickref.me [appears](https://quickref.me/mysql#proccess) to lag behind with updates [by more than a year](https://github.com/Fechin/reference/commit/e743fe9e25243d723660377b5e842fe6b83af8fd)
* and has some extra JavaScript tucked in there from two purported [advertising](https://www.virustotal.com/gui/domain/a.ad.gt) [networks](https://www.virustotal.com/gui/domain/devcdn.intergi.com)

There are tacit acknowledgements both [in the code](https://github.com/Fechin/reference/blame/3db8687a1c7fc3fb53b3bb66c4bd9a2100cb1ac9/source/_posts/vim.md#L39) and [the issue tracker](https://github.com/Fechin/reference/issues/137) that you're in control of both sites, so I presume one is just as legit as the other, and not some third party just capitalizing off your work.

If the goal was to make some money on the side, clearly that's fine; you [and Randy8080](https://github.com/Randy8080?tab=overview&from=2020-03-01&to=2021-05-31) in particular have put a lot of effort into this, and reward is due.

However, it would help to be up-front about that, particularly since [the "Contributing" section of the README](https://github.com/Fechin/reference?tab=readme-ov-file#-contributing) doesn't mention anything explicitly about the terms or licensing of user contributions.

![Screenshot of cheatsheets.zip vs. quickref.me, with respect to a cdn.intergient.com JavaScript asset](https://github.com/user-attachments/assets/61bae5d4-4a40-4769-ba32-7d38e011a316)

![Screenshot of cheatsheets.zip vs. quickref.me, with respect to an a.ad.gt JavaScript asset](https://github.com/user-attachments/assets/8430f045-8733-4429-b2f8-6f023dd3f81f)

Cheers,
Kevin

**Comment by Fechin** [comment]
Hey Kevin,

That's a really good question! So, [quickref.me](quickref.me) was actually the original domain name for this project. However, about a year ago, it got acquired by a company based in the US. To ensure the continuity and stability of this open-source, we then moved to the [cheatsheets.zip](cheatsheets.zip) domain (of course, all within the bounds of the agreements in place).

Why quickref.me hasn’t been kept up-to-date and why tracking code hasn’t been swapped out for something of our own is a bit of a mystery to me too.

Hope that clears things up a bit!

Cheers,
Fechin

**Comment by ernstki** [comment]
Oh, I'm sorry to hear that. Thanks for your response.

I still think it could be helpful to mention this in a very up-front way in the README, so that there isn't confusion. That other company could insert _anything_ into their JavaScript, and if it's beyond your control to stop that, this might reflect poorly on your project, and the efforts of your contributors.

As it stands, there isn't ample differentiation between the two sites (unless one looks more deeply).

**Comment by Fechin** [comment]
Thanks for pointing that out. I've gone ahead and updated the README to clarify the relationship between cheatsheets.zip and quickref.me. It should be much clearer now!
